// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: client.proto

#ifndef PROTOBUF_client_2eproto__INCLUDED
#define PROTOBUF_client_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 2005000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 2005000 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)

namespace Ennovia {

// Internal implementation detail -- do not call these.
void  protobuf_AddDesc_client_2eproto();
void protobuf_AssignDesc_client_2eproto();
void protobuf_ShutdownFile_client_2eproto();

class TextMessage;
class GetTileOptionList;
class GetLocatableOptionList;
class ChooseOption;
class GetLocatablePosition;
class GetLocatableIntroduction;
class WalkTo;
class Credentials;
class SendAESKey;
class RequestMapData;

// ===================================================================

class TextMessage : public ::google::protobuf::Message {
 public:
  TextMessage();
  virtual ~TextMessage();

  TextMessage(const TextMessage& from);

  inline TextMessage& operator=(const TextMessage& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const TextMessage& default_instance();

  void Swap(TextMessage* other);

  // implements Message ----------------------------------------------

  TextMessage* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const TextMessage& from);
  void MergeFrom(const TextMessage& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // required string text = 1;
  inline bool has_text() const;
  inline void clear_text();
  static const int kTextFieldNumber = 1;
  inline const ::std::string& text() const;
  inline void set_text(const ::std::string& value);
  inline void set_text(const char* value);
  inline void set_text(const char* value, size_t size);
  inline ::std::string* mutable_text();
  inline ::std::string* release_text();
  inline void set_allocated_text(::std::string* text);

  // @@protoc_insertion_point(class_scope:Ennovia.TextMessage)
 private:
  inline void set_has_text();
  inline void clear_has_text();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::std::string* text_;

  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(1 + 31) / 32];

  friend void  protobuf_AddDesc_client_2eproto();
  friend void protobuf_AssignDesc_client_2eproto();
  friend void protobuf_ShutdownFile_client_2eproto();

  void InitAsDefaultInstance();
  static TextMessage* default_instance_;
};
// -------------------------------------------------------------------

class GetTileOptionList : public ::google::protobuf::Message {
 public:
  GetTileOptionList();
  virtual ~GetTileOptionList();

  GetTileOptionList(const GetTileOptionList& from);

  inline GetTileOptionList& operator=(const GetTileOptionList& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const GetTileOptionList& default_instance();

  void Swap(GetTileOptionList* other);

  // implements Message ----------------------------------------------

  GetTileOptionList* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const GetTileOptionList& from);
  void MergeFrom(const GetTileOptionList& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // required int32 map = 1;
  inline bool has_map() const;
  inline void clear_map();
  static const int kMapFieldNumber = 1;
  inline ::google::protobuf::int32 map() const;
  inline void set_map(::google::protobuf::int32 value);

  // required int32 x = 2;
  inline bool has_x() const;
  inline void clear_x();
  static const int kXFieldNumber = 2;
  inline ::google::protobuf::int32 x() const;
  inline void set_x(::google::protobuf::int32 value);

  // required int32 y = 3;
  inline bool has_y() const;
  inline void clear_y();
  static const int kYFieldNumber = 3;
  inline ::google::protobuf::int32 y() const;
  inline void set_y(::google::protobuf::int32 value);

  // @@protoc_insertion_point(class_scope:Ennovia.GetTileOptionList)
 private:
  inline void set_has_map();
  inline void clear_has_map();
  inline void set_has_x();
  inline void clear_has_x();
  inline void set_has_y();
  inline void clear_has_y();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::google::protobuf::int32 map_;
  ::google::protobuf::int32 x_;
  ::google::protobuf::int32 y_;

  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(3 + 31) / 32];

  friend void  protobuf_AddDesc_client_2eproto();
  friend void protobuf_AssignDesc_client_2eproto();
  friend void protobuf_ShutdownFile_client_2eproto();

  void InitAsDefaultInstance();
  static GetTileOptionList* default_instance_;
};
// -------------------------------------------------------------------

class GetLocatableOptionList : public ::google::protobuf::Message {
 public:
  GetLocatableOptionList();
  virtual ~GetLocatableOptionList();

  GetLocatableOptionList(const GetLocatableOptionList& from);

  inline GetLocatableOptionList& operator=(const GetLocatableOptionList& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const GetLocatableOptionList& default_instance();

  void Swap(GetLocatableOptionList* other);

  // implements Message ----------------------------------------------

  GetLocatableOptionList* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const GetLocatableOptionList& from);
  void MergeFrom(const GetLocatableOptionList& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // required int32 id = 1;
  inline bool has_id() const;
  inline void clear_id();
  static const int kIdFieldNumber = 1;
  inline ::google::protobuf::int32 id() const;
  inline void set_id(::google::protobuf::int32 value);

  // @@protoc_insertion_point(class_scope:Ennovia.GetLocatableOptionList)
 private:
  inline void set_has_id();
  inline void clear_has_id();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::google::protobuf::int32 id_;

  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(1 + 31) / 32];

  friend void  protobuf_AddDesc_client_2eproto();
  friend void protobuf_AssignDesc_client_2eproto();
  friend void protobuf_ShutdownFile_client_2eproto();

  void InitAsDefaultInstance();
  static GetLocatableOptionList* default_instance_;
};
// -------------------------------------------------------------------

class ChooseOption : public ::google::protobuf::Message {
 public:
  ChooseOption();
  virtual ~ChooseOption();

  ChooseOption(const ChooseOption& from);

  inline ChooseOption& operator=(const ChooseOption& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const ChooseOption& default_instance();

  void Swap(ChooseOption* other);

  // implements Message ----------------------------------------------

  ChooseOption* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const ChooseOption& from);
  void MergeFrom(const ChooseOption& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // required int32 optionlist = 1;
  inline bool has_optionlist() const;
  inline void clear_optionlist();
  static const int kOptionlistFieldNumber = 1;
  inline ::google::protobuf::int32 optionlist() const;
  inline void set_optionlist(::google::protobuf::int32 value);

  // required int32 id = 2;
  inline bool has_id() const;
  inline void clear_id();
  static const int kIdFieldNumber = 2;
  inline ::google::protobuf::int32 id() const;
  inline void set_id(::google::protobuf::int32 value);

  // @@protoc_insertion_point(class_scope:Ennovia.ChooseOption)
 private:
  inline void set_has_optionlist();
  inline void clear_has_optionlist();
  inline void set_has_id();
  inline void clear_has_id();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::google::protobuf::int32 optionlist_;
  ::google::protobuf::int32 id_;

  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(2 + 31) / 32];

  friend void  protobuf_AddDesc_client_2eproto();
  friend void protobuf_AssignDesc_client_2eproto();
  friend void protobuf_ShutdownFile_client_2eproto();

  void InitAsDefaultInstance();
  static ChooseOption* default_instance_;
};
// -------------------------------------------------------------------

class GetLocatablePosition : public ::google::protobuf::Message {
 public:
  GetLocatablePosition();
  virtual ~GetLocatablePosition();

  GetLocatablePosition(const GetLocatablePosition& from);

  inline GetLocatablePosition& operator=(const GetLocatablePosition& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const GetLocatablePosition& default_instance();

  void Swap(GetLocatablePosition* other);

  // implements Message ----------------------------------------------

  GetLocatablePosition* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const GetLocatablePosition& from);
  void MergeFrom(const GetLocatablePosition& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // required int32 id = 1;
  inline bool has_id() const;
  inline void clear_id();
  static const int kIdFieldNumber = 1;
  inline ::google::protobuf::int32 id() const;
  inline void set_id(::google::protobuf::int32 value);

  // @@protoc_insertion_point(class_scope:Ennovia.GetLocatablePosition)
 private:
  inline void set_has_id();
  inline void clear_has_id();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::google::protobuf::int32 id_;

  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(1 + 31) / 32];

  friend void  protobuf_AddDesc_client_2eproto();
  friend void protobuf_AssignDesc_client_2eproto();
  friend void protobuf_ShutdownFile_client_2eproto();

  void InitAsDefaultInstance();
  static GetLocatablePosition* default_instance_;
};
// -------------------------------------------------------------------

class GetLocatableIntroduction : public ::google::protobuf::Message {
 public:
  GetLocatableIntroduction();
  virtual ~GetLocatableIntroduction();

  GetLocatableIntroduction(const GetLocatableIntroduction& from);

  inline GetLocatableIntroduction& operator=(const GetLocatableIntroduction& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const GetLocatableIntroduction& default_instance();

  void Swap(GetLocatableIntroduction* other);

  // implements Message ----------------------------------------------

  GetLocatableIntroduction* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const GetLocatableIntroduction& from);
  void MergeFrom(const GetLocatableIntroduction& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // required int32 id = 1;
  inline bool has_id() const;
  inline void clear_id();
  static const int kIdFieldNumber = 1;
  inline ::google::protobuf::int32 id() const;
  inline void set_id(::google::protobuf::int32 value);

  // @@protoc_insertion_point(class_scope:Ennovia.GetLocatableIntroduction)
 private:
  inline void set_has_id();
  inline void clear_has_id();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::google::protobuf::int32 id_;

  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(1 + 31) / 32];

  friend void  protobuf_AddDesc_client_2eproto();
  friend void protobuf_AssignDesc_client_2eproto();
  friend void protobuf_ShutdownFile_client_2eproto();

  void InitAsDefaultInstance();
  static GetLocatableIntroduction* default_instance_;
};
// -------------------------------------------------------------------

class WalkTo : public ::google::protobuf::Message {
 public:
  WalkTo();
  virtual ~WalkTo();

  WalkTo(const WalkTo& from);

  inline WalkTo& operator=(const WalkTo& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const WalkTo& default_instance();

  void Swap(WalkTo* other);

  // implements Message ----------------------------------------------

  WalkTo* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const WalkTo& from);
  void MergeFrom(const WalkTo& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // required float x = 1;
  inline bool has_x() const;
  inline void clear_x();
  static const int kXFieldNumber = 1;
  inline float x() const;
  inline void set_x(float value);

  // required float y = 2;
  inline bool has_y() const;
  inline void clear_y();
  static const int kYFieldNumber = 2;
  inline float y() const;
  inline void set_y(float value);

  // @@protoc_insertion_point(class_scope:Ennovia.WalkTo)
 private:
  inline void set_has_x();
  inline void clear_has_x();
  inline void set_has_y();
  inline void clear_has_y();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  float x_;
  float y_;

  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(2 + 31) / 32];

  friend void  protobuf_AddDesc_client_2eproto();
  friend void protobuf_AssignDesc_client_2eproto();
  friend void protobuf_ShutdownFile_client_2eproto();

  void InitAsDefaultInstance();
  static WalkTo* default_instance_;
};
// -------------------------------------------------------------------

class Credentials : public ::google::protobuf::Message {
 public:
  Credentials();
  virtual ~Credentials();

  Credentials(const Credentials& from);

  inline Credentials& operator=(const Credentials& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const Credentials& default_instance();

  void Swap(Credentials* other);

  // implements Message ----------------------------------------------

  Credentials* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const Credentials& from);
  void MergeFrom(const Credentials& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // required string username = 1;
  inline bool has_username() const;
  inline void clear_username();
  static const int kUsernameFieldNumber = 1;
  inline const ::std::string& username() const;
  inline void set_username(const ::std::string& value);
  inline void set_username(const char* value);
  inline void set_username(const char* value, size_t size);
  inline ::std::string* mutable_username();
  inline ::std::string* release_username();
  inline void set_allocated_username(::std::string* username);

  // required string password = 2;
  inline bool has_password() const;
  inline void clear_password();
  static const int kPasswordFieldNumber = 2;
  inline const ::std::string& password() const;
  inline void set_password(const ::std::string& value);
  inline void set_password(const char* value);
  inline void set_password(const char* value, size_t size);
  inline ::std::string* mutable_password();
  inline ::std::string* release_password();
  inline void set_allocated_password(::std::string* password);

  // @@protoc_insertion_point(class_scope:Ennovia.Credentials)
 private:
  inline void set_has_username();
  inline void clear_has_username();
  inline void set_has_password();
  inline void clear_has_password();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::std::string* username_;
  ::std::string* password_;

  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(2 + 31) / 32];

  friend void  protobuf_AddDesc_client_2eproto();
  friend void protobuf_AssignDesc_client_2eproto();
  friend void protobuf_ShutdownFile_client_2eproto();

  void InitAsDefaultInstance();
  static Credentials* default_instance_;
};
// -------------------------------------------------------------------

class SendAESKey : public ::google::protobuf::Message {
 public:
  SendAESKey();
  virtual ~SendAESKey();

  SendAESKey(const SendAESKey& from);

  inline SendAESKey& operator=(const SendAESKey& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const SendAESKey& default_instance();

  void Swap(SendAESKey* other);

  // implements Message ----------------------------------------------

  SendAESKey* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const SendAESKey& from);
  void MergeFrom(const SendAESKey& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // @@protoc_insertion_point(class_scope:Ennovia.SendAESKey)
 private:

  ::google::protobuf::UnknownFieldSet _unknown_fields_;


  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[1];

  friend void  protobuf_AddDesc_client_2eproto();
  friend void protobuf_AssignDesc_client_2eproto();
  friend void protobuf_ShutdownFile_client_2eproto();

  void InitAsDefaultInstance();
  static SendAESKey* default_instance_;
};
// -------------------------------------------------------------------

class RequestMapData : public ::google::protobuf::Message {
 public:
  RequestMapData();
  virtual ~RequestMapData();

  RequestMapData(const RequestMapData& from);

  inline RequestMapData& operator=(const RequestMapData& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const RequestMapData& default_instance();

  void Swap(RequestMapData* other);

  // implements Message ----------------------------------------------

  RequestMapData* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const RequestMapData& from);
  void MergeFrom(const RequestMapData& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // required int32 id = 1;
  inline bool has_id() const;
  inline void clear_id();
  static const int kIdFieldNumber = 1;
  inline ::google::protobuf::int32 id() const;
  inline void set_id(::google::protobuf::int32 value);

  // @@protoc_insertion_point(class_scope:Ennovia.RequestMapData)
 private:
  inline void set_has_id();
  inline void clear_has_id();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::google::protobuf::int32 id_;

  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(1 + 31) / 32];

  friend void  protobuf_AddDesc_client_2eproto();
  friend void protobuf_AssignDesc_client_2eproto();
  friend void protobuf_ShutdownFile_client_2eproto();

  void InitAsDefaultInstance();
  static RequestMapData* default_instance_;
};
// ===================================================================


// ===================================================================

// TextMessage

// required string text = 1;
inline bool TextMessage::has_text() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void TextMessage::set_has_text() {
  _has_bits_[0] |= 0x00000001u;
}
inline void TextMessage::clear_has_text() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void TextMessage::clear_text() {
  if (text_ != &::google::protobuf::internal::kEmptyString) {
    text_->clear();
  }
  clear_has_text();
}
inline const ::std::string& TextMessage::text() const {
  return *text_;
}
inline void TextMessage::set_text(const ::std::string& value) {
  set_has_text();
  if (text_ == &::google::protobuf::internal::kEmptyString) {
    text_ = new ::std::string;
  }
  text_->assign(value);
}
inline void TextMessage::set_text(const char* value) {
  set_has_text();
  if (text_ == &::google::protobuf::internal::kEmptyString) {
    text_ = new ::std::string;
  }
  text_->assign(value);
}
inline void TextMessage::set_text(const char* value, size_t size) {
  set_has_text();
  if (text_ == &::google::protobuf::internal::kEmptyString) {
    text_ = new ::std::string;
  }
  text_->assign(reinterpret_cast<const char*>(value), size);
}
inline ::std::string* TextMessage::mutable_text() {
  set_has_text();
  if (text_ == &::google::protobuf::internal::kEmptyString) {
    text_ = new ::std::string;
  }
  return text_;
}
inline ::std::string* TextMessage::release_text() {
  clear_has_text();
  if (text_ == &::google::protobuf::internal::kEmptyString) {
    return NULL;
  } else {
    ::std::string* temp = text_;
    text_ = const_cast< ::std::string*>(&::google::protobuf::internal::kEmptyString);
    return temp;
  }
}
inline void TextMessage::set_allocated_text(::std::string* text) {
  if (text_ != &::google::protobuf::internal::kEmptyString) {
    delete text_;
  }
  if (text) {
    set_has_text();
    text_ = text;
  } else {
    clear_has_text();
    text_ = const_cast< ::std::string*>(&::google::protobuf::internal::kEmptyString);
  }
}

// -------------------------------------------------------------------

// GetTileOptionList

// required int32 map = 1;
inline bool GetTileOptionList::has_map() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void GetTileOptionList::set_has_map() {
  _has_bits_[0] |= 0x00000001u;
}
inline void GetTileOptionList::clear_has_map() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void GetTileOptionList::clear_map() {
  map_ = 0;
  clear_has_map();
}
inline ::google::protobuf::int32 GetTileOptionList::map() const {
  return map_;
}
inline void GetTileOptionList::set_map(::google::protobuf::int32 value) {
  set_has_map();
  map_ = value;
}

// required int32 x = 2;
inline bool GetTileOptionList::has_x() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void GetTileOptionList::set_has_x() {
  _has_bits_[0] |= 0x00000002u;
}
inline void GetTileOptionList::clear_has_x() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void GetTileOptionList::clear_x() {
  x_ = 0;
  clear_has_x();
}
inline ::google::protobuf::int32 GetTileOptionList::x() const {
  return x_;
}
inline void GetTileOptionList::set_x(::google::protobuf::int32 value) {
  set_has_x();
  x_ = value;
}

// required int32 y = 3;
inline bool GetTileOptionList::has_y() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
inline void GetTileOptionList::set_has_y() {
  _has_bits_[0] |= 0x00000004u;
}
inline void GetTileOptionList::clear_has_y() {
  _has_bits_[0] &= ~0x00000004u;
}
inline void GetTileOptionList::clear_y() {
  y_ = 0;
  clear_has_y();
}
inline ::google::protobuf::int32 GetTileOptionList::y() const {
  return y_;
}
inline void GetTileOptionList::set_y(::google::protobuf::int32 value) {
  set_has_y();
  y_ = value;
}

// -------------------------------------------------------------------

// GetLocatableOptionList

// required int32 id = 1;
inline bool GetLocatableOptionList::has_id() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void GetLocatableOptionList::set_has_id() {
  _has_bits_[0] |= 0x00000001u;
}
inline void GetLocatableOptionList::clear_has_id() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void GetLocatableOptionList::clear_id() {
  id_ = 0;
  clear_has_id();
}
inline ::google::protobuf::int32 GetLocatableOptionList::id() const {
  return id_;
}
inline void GetLocatableOptionList::set_id(::google::protobuf::int32 value) {
  set_has_id();
  id_ = value;
}

// -------------------------------------------------------------------

// ChooseOption

// required int32 optionlist = 1;
inline bool ChooseOption::has_optionlist() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void ChooseOption::set_has_optionlist() {
  _has_bits_[0] |= 0x00000001u;
}
inline void ChooseOption::clear_has_optionlist() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void ChooseOption::clear_optionlist() {
  optionlist_ = 0;
  clear_has_optionlist();
}
inline ::google::protobuf::int32 ChooseOption::optionlist() const {
  return optionlist_;
}
inline void ChooseOption::set_optionlist(::google::protobuf::int32 value) {
  set_has_optionlist();
  optionlist_ = value;
}

// required int32 id = 2;
inline bool ChooseOption::has_id() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void ChooseOption::set_has_id() {
  _has_bits_[0] |= 0x00000002u;
}
inline void ChooseOption::clear_has_id() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void ChooseOption::clear_id() {
  id_ = 0;
  clear_has_id();
}
inline ::google::protobuf::int32 ChooseOption::id() const {
  return id_;
}
inline void ChooseOption::set_id(::google::protobuf::int32 value) {
  set_has_id();
  id_ = value;
}

// -------------------------------------------------------------------

// GetLocatablePosition

// required int32 id = 1;
inline bool GetLocatablePosition::has_id() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void GetLocatablePosition::set_has_id() {
  _has_bits_[0] |= 0x00000001u;
}
inline void GetLocatablePosition::clear_has_id() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void GetLocatablePosition::clear_id() {
  id_ = 0;
  clear_has_id();
}
inline ::google::protobuf::int32 GetLocatablePosition::id() const {
  return id_;
}
inline void GetLocatablePosition::set_id(::google::protobuf::int32 value) {
  set_has_id();
  id_ = value;
}

// -------------------------------------------------------------------

// GetLocatableIntroduction

// required int32 id = 1;
inline bool GetLocatableIntroduction::has_id() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void GetLocatableIntroduction::set_has_id() {
  _has_bits_[0] |= 0x00000001u;
}
inline void GetLocatableIntroduction::clear_has_id() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void GetLocatableIntroduction::clear_id() {
  id_ = 0;
  clear_has_id();
}
inline ::google::protobuf::int32 GetLocatableIntroduction::id() const {
  return id_;
}
inline void GetLocatableIntroduction::set_id(::google::protobuf::int32 value) {
  set_has_id();
  id_ = value;
}

// -------------------------------------------------------------------

// WalkTo

// required float x = 1;
inline bool WalkTo::has_x() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void WalkTo::set_has_x() {
  _has_bits_[0] |= 0x00000001u;
}
inline void WalkTo::clear_has_x() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void WalkTo::clear_x() {
  x_ = 0;
  clear_has_x();
}
inline float WalkTo::x() const {
  return x_;
}
inline void WalkTo::set_x(float value) {
  set_has_x();
  x_ = value;
}

// required float y = 2;
inline bool WalkTo::has_y() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void WalkTo::set_has_y() {
  _has_bits_[0] |= 0x00000002u;
}
inline void WalkTo::clear_has_y() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void WalkTo::clear_y() {
  y_ = 0;
  clear_has_y();
}
inline float WalkTo::y() const {
  return y_;
}
inline void WalkTo::set_y(float value) {
  set_has_y();
  y_ = value;
}

// -------------------------------------------------------------------

// Credentials

// required string username = 1;
inline bool Credentials::has_username() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void Credentials::set_has_username() {
  _has_bits_[0] |= 0x00000001u;
}
inline void Credentials::clear_has_username() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void Credentials::clear_username() {
  if (username_ != &::google::protobuf::internal::kEmptyString) {
    username_->clear();
  }
  clear_has_username();
}
inline const ::std::string& Credentials::username() const {
  return *username_;
}
inline void Credentials::set_username(const ::std::string& value) {
  set_has_username();
  if (username_ == &::google::protobuf::internal::kEmptyString) {
    username_ = new ::std::string;
  }
  username_->assign(value);
}
inline void Credentials::set_username(const char* value) {
  set_has_username();
  if (username_ == &::google::protobuf::internal::kEmptyString) {
    username_ = new ::std::string;
  }
  username_->assign(value);
}
inline void Credentials::set_username(const char* value, size_t size) {
  set_has_username();
  if (username_ == &::google::protobuf::internal::kEmptyString) {
    username_ = new ::std::string;
  }
  username_->assign(reinterpret_cast<const char*>(value), size);
}
inline ::std::string* Credentials::mutable_username() {
  set_has_username();
  if (username_ == &::google::protobuf::internal::kEmptyString) {
    username_ = new ::std::string;
  }
  return username_;
}
inline ::std::string* Credentials::release_username() {
  clear_has_username();
  if (username_ == &::google::protobuf::internal::kEmptyString) {
    return NULL;
  } else {
    ::std::string* temp = username_;
    username_ = const_cast< ::std::string*>(&::google::protobuf::internal::kEmptyString);
    return temp;
  }
}
inline void Credentials::set_allocated_username(::std::string* username) {
  if (username_ != &::google::protobuf::internal::kEmptyString) {
    delete username_;
  }
  if (username) {
    set_has_username();
    username_ = username;
  } else {
    clear_has_username();
    username_ = const_cast< ::std::string*>(&::google::protobuf::internal::kEmptyString);
  }
}

// required string password = 2;
inline bool Credentials::has_password() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void Credentials::set_has_password() {
  _has_bits_[0] |= 0x00000002u;
}
inline void Credentials::clear_has_password() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void Credentials::clear_password() {
  if (password_ != &::google::protobuf::internal::kEmptyString) {
    password_->clear();
  }
  clear_has_password();
}
inline const ::std::string& Credentials::password() const {
  return *password_;
}
inline void Credentials::set_password(const ::std::string& value) {
  set_has_password();
  if (password_ == &::google::protobuf::internal::kEmptyString) {
    password_ = new ::std::string;
  }
  password_->assign(value);
}
inline void Credentials::set_password(const char* value) {
  set_has_password();
  if (password_ == &::google::protobuf::internal::kEmptyString) {
    password_ = new ::std::string;
  }
  password_->assign(value);
}
inline void Credentials::set_password(const char* value, size_t size) {
  set_has_password();
  if (password_ == &::google::protobuf::internal::kEmptyString) {
    password_ = new ::std::string;
  }
  password_->assign(reinterpret_cast<const char*>(value), size);
}
inline ::std::string* Credentials::mutable_password() {
  set_has_password();
  if (password_ == &::google::protobuf::internal::kEmptyString) {
    password_ = new ::std::string;
  }
  return password_;
}
inline ::std::string* Credentials::release_password() {
  clear_has_password();
  if (password_ == &::google::protobuf::internal::kEmptyString) {
    return NULL;
  } else {
    ::std::string* temp = password_;
    password_ = const_cast< ::std::string*>(&::google::protobuf::internal::kEmptyString);
    return temp;
  }
}
inline void Credentials::set_allocated_password(::std::string* password) {
  if (password_ != &::google::protobuf::internal::kEmptyString) {
    delete password_;
  }
  if (password) {
    set_has_password();
    password_ = password;
  } else {
    clear_has_password();
    password_ = const_cast< ::std::string*>(&::google::protobuf::internal::kEmptyString);
  }
}

// -------------------------------------------------------------------

// SendAESKey

// -------------------------------------------------------------------

// RequestMapData

// required int32 id = 1;
inline bool RequestMapData::has_id() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void RequestMapData::set_has_id() {
  _has_bits_[0] |= 0x00000001u;
}
inline void RequestMapData::clear_has_id() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void RequestMapData::clear_id() {
  id_ = 0;
  clear_has_id();
}
inline ::google::protobuf::int32 RequestMapData::id() const {
  return id_;
}
inline void RequestMapData::set_id(::google::protobuf::int32 value) {
  set_has_id();
  id_ = value;
}


// @@protoc_insertion_point(namespace_scope)

}  // namespace Ennovia

#ifndef SWIG
namespace google {
namespace protobuf {


}  // namespace google
}  // namespace protobuf
#endif  // SWIG

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_client_2eproto__INCLUDED
